### ISSUE TITLE
Display error message for invalid credentials.

### ISSUE THREAD

**Issue by Pradusha-Timalsina** [Pradusha-Timalsina/Bakery-Management-System#16]
Error messages is not displayed.
![image](https://user-images.githubusercontent.com/128008234/235858480-c8ed1aa7-eeea-4295-bf20-7e3d93bde6aa.png)

**Comment by Fakron** [comment]
Issues fixed.
you can check it on commit 0e13d6ff8fa7b67d18e4b55a89c620136b546f3e
![Screenshot from 2023-05-03 13-45-51](https://user-images.githubusercontent.com/76208585/235862641-54d5faac-ee68-4d8d-81cd-3cd2692b85e7.png)
@Pradusha-Timalsina @Kamana73

**Comment by Kamana73** [comment]
Checked

**Comment by Pradusha-Timalsina** [comment]
Checked it✅
