### ISSUE TITLE
Add error handling for register forms.

### ISSUE THREAD

**Issue by Pradusha-Timalsina** [Pradusha-Timalsina/Bakery-Management-System#17]
![image](https://user-images.githubusercontent.com/128008234/235859157-461c4965-9873-4e00-990a-4ca480ab3547.png)

![image](https://user-images.githubusercontent.com/128008234/235859182-6b7b33c7-69ae-4a33-a944-15104d195f16.png)

**Comment by Fakron** [comment]
Issues fixed.
You can check it on commit 0e13d6ff8fa7b67d18e4b55a89c620136b546f3e
@Pradusha-Ti @Kamana73 
![Screenshot from 2023-05-03 13-45-58](https://user-images.githubusercontent.com/76208585/235862846-5803997d-655d-4f56-88da-8f51d33c11ce.png)
malsina 
![Screenshot from 2023-05-03 13-48-07](https://user-images.githubusercontent.com/76208585/235862873-ea553dd2-cdd4-4781-91cb-b692a4ca94c3.png)

**Comment by Kamana73** [comment]
Checked
